services:  
  keycloak:
    ports:
      - "8888:8080"
    image: jboss/keycloak
    container_name: keycloak
    environment:
      KEYCLOAK_USER: spring
      KEYCLOAK_PASSWORD: spring
networks: 
  default: 
    name: microservice    