version: "3"

services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    healthcheck:
      test: "exit 0"          
  mysqldb:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: patient  
    ports:
      - "3307:3306"    
    healthcheck:
      test: "exit 0"           
  microservice-config-server:
    build:
      context: ./microservice-configserver/
    ports:
      - "9101:9101"
    image: configserver          
  microservice-patienthistory:
    build:
      context: ./microservice-patienthistory/
    ports:
      - "8082:8082"
    environment:  
        MONGODB_HOST: mongodb   
        DOCKER_CONFIG_SERVER_URL: http://microservice-configserver:9101
    image: patienthistory
    depends_on:     
      mongodb:
        condition: service_healthy
    restart: on-failure        
  microservice-patient:
    build:
      context: ./microservice-patient/
    ports:
      - "8081:8081"
    environment:  
        SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/patient?serverTimezone=UTC&autoReconnect=true 
        DOCKER_CONFIG_SERVER_URL: http://microservice-configserver:9101  
    image: patient
    depends_on:     
      mysqldb:
        condition: service_healthy
    restart: on-failure      
  microservice-expert:
    build:
      context: ./microservice-expert/
    ports:
      - "8083:8083"
    environment:  
        SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/patient?serverTimezone=UTC&autoReconnect=true   
        DOCKER_CONFIG_SERVER_URL: http://microservice-configserver:9101
    image: expert
    depends_on:     
      mysqldb:
        condition: service_healthy
    restart: on-failure    
  microservice-clientui:
    build:
      context: ./microservice-clientui/
    ports:
      - "8080:8080"
    environment:
      DOCKER_PATIENT_URL: http://microservice-patient:8081  
      DOCKER_PATIENT_HISTORY_URL: http://microservice-patienthistory:8082
      DOCKER_EXPERT_URL: http://microservice-expert:8083    
      DOCKER_CONFIG_SERVER_URL: http://microservice-configserver:9101
    image: clientui
    depends_on:     
      microservice-patient:
        condition: service_started
      microservice-patienthistory:
        condition: service_started  
      microservice-expert:
        condition: service_started    
