version: "3"

services:
  microservice-configserver:
    build:
      context: ./microservice-configserver/
    ports:
      - "9101:9101"
    image: configserver
    healthcheck:
        test: [ "CMD", "curl", "-f", "http://microservice-configserver:9101/microservice-eurekaserver/default" ]
        interval: 10s
        timeout: 5s
        retries: 5
  microservice-eurekaserver:
    build:
       context: ./microservice-eurekaserver/
    ports:
       - "8761:8761"
    environment:
      DOCKER_CONFIG_SERVER_URL: http://microservice-configserver:9101
      DOCKER_EUREKA_SERVER_URL: http://microservice-eurekaserver:8761/eureka
    image: eureka-server
    depends_on:
     microservice-configserver:
      condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://microservice-eurekaserver:8761" ]
      interval: 10s
      timeout: 5s
      retries: 5
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    healthcheck:
      test: "exit 0"
  mysqldb:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: patient  
    ports:
      - "3307:3306"    
    healthcheck:
      test: "exit 0"             
  microservice-patienthistory:
    build:
      context: ./microservice-patienthistory/
    ports:
      - "8082:8082"
    environment:
        MONGODB_HOST: mongodb
        DOCKER_CONFIG_SERVER_URL: http://microservice-configserver:9101
        DOCKER_EUREKA_SERVER_URL: http://microservice-eurekaserver:8761/eureka
        DOCKER_ZIPKIN_URL: http://zipkin:9411/api/v2/spans
        DOCKER_KEYCLOCK_URL : http://keyclock:8080
    image: patienthistory
    depends_on:
      mongodb:
        condition: service_healthy
      microservice-configserver:
       condition: service_healthy
      microservice-eurekaserver:
       condition: service_healthy
      zipkin: 
       condition: service_healthy
    restart: on-failure
  microservice-patient:
    build:
      context: ./microservice-patient/
    ports:
      - "8081:8081"
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/patient?serverTimezone=UTC&autoReconnect=true
        DOCKER_CONFIG_SERVER_URL: http://microservice-configserver:9101
        DOCKER_EUREKA_SERVER_URL: http://microservice-eurekaserver:8761/eureka
        DOCKER_ZIPKIN_URL: http://zipkin:9411/api/v2/spans
        DOCKER_KEYCLOCK_URL : http://keyclock:8080
    image: patient
    depends_on:
      mysqldb:
        condition: service_healthy
      microservice-configserver:
       condition: service_healthy
      microservice-eurekaserver:
        condition: service_healthy
      zipkin: 
       condition: service_healthy  
    restart: on-failure
  microservice-expert:
    build:
      context: ./microservice-expert/
    ports:
      - "8083:8083"
    environment:  
        SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/patient?serverTimezone=UTC&autoReconnect=true
        DOCKER_CONFIG_SERVER_URL: http://microservice-configserver:9101
        DOCKER_EUREKA_SERVER_URL: http://microservice-eurekaserver:8761/eureka
        DOCKER_ZIPKIN_URL: http://zipkin:9411/api/v2/spans
        DOCKER_KEYCLOCK_URL : http://keyclock:8080
    image: expert
    depends_on:
      mysqldb:
        condition: service_healthy
      microservice-configserver:
        condition: service_healthy
      microservice-eurekaserver: 
        condition: service_healthy
      zipkin: 
        condition: service_healthy  
    restart: on-failure    
  microservice-gateway:
    build:
      context: ./microservice-gateway/
    ports:
      - "8084:8084"
    environment:
        DOCKER_CONFIG_SERVER_URL: http://microservice-configserver:9101
        DOCKER_EUREKA_SERVER_URL: http://microservice-eurekaserver:8761/eureka
        DOCKER_ZIPKIN_URL: http://zipkin:9411/api/v2/spans
    image: gateway
    depends_on:
      microservice-configserver:
       condition: service_healthy
      microservice-eurekaserver:
       condition: service_healthy
      microservice-expert:
       condition: service_started
      microservice-patient:
       condition: service_started 
      microservice-patienthistory:
       condition: service_started       
      zipkin: 
       condition: service_healthy
    restart: on-failure      
  microservice-clientui:
    build:
      context: ./microservice-clientui/
    ports:
      - "8080:8080"
    environment:
      DOCKER_CONFIG_SERVER_URL: http://microservice-configserver:9101
      DOCKER_EUREKA_SERVER_URL: http://microservice-eurekaserver:8761/eureka
      DOCKER_ZIPKIN_URL: http://zipkin:9411/api/v2/spans
      DOCKER_KEYCLOCK_URL : http://keyclock
    image: clientui
    depends_on:
      microservice-configserver:
        condition: service_healthy
      microservice-eurekaserver: 
        condition: service_healthy
      microservice-patient:
        condition: service_started
      microservice-patienthistory:
        condition: service_started
      microservice-expert:
        condition: service_started
      microservice-gateway:
        condition: service_started
      zipkin: 
        condition: service_healthy  

        
        
 