spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: ${DOCKER_KEYCLOAK_ISSUER_URL:http://localhost:8888}/auth/realms/master
        registration:
          gateway:
            provider: keycloak
            client-id: gateway
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
