spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${DOCKER_KEYCLOAK_TOKEN_URL:http://localhost:8888}/auth/realms/master/protocol/openid-connect/token
            authorization-uri: ${DOCKER_KEYCLOAK_AUTHORIZATION_URL:http://localhost:8888}/auth/realms/master/protocol/openid-connect/auth
            user-info-uri: ${DOCKER_KEYCLOAK_USERINFO_URL:http://localhost:8888}/auth/realms/master/protocol/openid-connect/userinfo
        registration:
          gateway:
            provider: keycloak
            client-id: gateway
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
