spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: microservice-patient
        uri: lb://microservice-patient
        predicates:
        - Path=/patient/**       
        filters:
        - SaveSession  
      - id: microservice-patienthistory
        uri: lb://microservice-patienthistory
        predicates:
        - Path=/patientHistory/**
        filters:
        - SaveSession
      - id: microservice-expert
        uri: lb://microservice-expert
        predicates:
        - Path=/expert/**
        filters:
        - SaveSession
        